### ISSUE TITLE
Unclear installation instructions

### ISSUE THREAD

**Issue by pmarcellino** [eventum/slack-unfurl#21]
I can't really tell how to use this app. Is this designed to run on a server and is just missing installation instructions?

**Comment by glensc** [comment]
It's designed to be run somewhere in the background and exposed to the internet, so slack servers can 
 do http post to it over https.
 
 Feel free to improve documentation by sending a PR.

**Comment by glensc** [comment]
how this works, is written in slack docs:
-  https://api.slack.com/reference/messaging/link-unfurling

the link ins the readme.
